### ISSUE TITLE
Empty argument and Banner not load(ex:run help banner).

### ISSUE THREAD

**Issue by omarkurt** [rotlogix/liffy#19]
root@ubuntu:/home/omar/Desktop/tool/liffy# **python liffy.py**

    .____    .__  _____  _____
    |    |   |__|/ ____\/ ____\__.__.
    |    |   |  \   __\   __<   |  |
    |    |___|  ||  |   |  |  \___  |
    |_______ \__||__|   |__|  / ____|v1.2
        \/                \/

[2015-04-26 00:33:40.985144] **Checking Target: None**
Traceback (most recent call last):
  File "liffy.py", line 146, in <module>
    main()
  File "liffy.py", line 89, in main
    parsed = urlparse.urlsplit(url)
  File "/usr/lib/python2.7/urlparse.py", line 182, in urlsplit
   **i = url.find(':')**
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by rotlogix** [comment]
I will check this out - thanks

**Comment by nestoru** [comment]
Any ETA for a resolution? As it is liffy won't run in Ubuntu 14.04 LTS
